title:       erbridge
email:       f@erbridge.co.uk
description: erbridge: freelance game / web developer available for hire

name: erbridge
author:
  name:  erbridge
  email: f@erbridge.co.uk

baseurl: ""
url:     http://erbridge.co.uk

contact-methods:
  - title: Twitter
    url:   https://twitter.com/erbridge
    class: twitter
  - title: GitHub
    url:   https://github.com/erbridge
    class: github
  - title: LinkedIn
    url:   https://www.linkedin.com/in/erbridge
    class: linkedin
  - title: Email
    url:   mailto:f@erbridge.co.uk
    class: email
  - title: RSS
    url:   /feed.xml
    class: rss

permalink: /blog/:year/:month/:day/:title/

defaults:
  - scope:
      path: pages
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: erbridge
  - scope:
      path: ""
      type: drafts
    values:
      layout: post
      author: erbridge

gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap

kramdown:
  input: GFM
  hard_wrap: true

exclude:
  - CNAME
  - README.md
  - bower.json
  - Gemfile*
